# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac6dfc3c2b59fa2e3c1034721d35929c72f280e30179092500f5f4da358c7cab0b12bbeaf028516c1c11cd9f0ea91c7c5362eb8585ccf20057df1cc62a0bda6c

test:
  secret_key_base: 259fc47cd37a0fd9c4852c55a72e887ed208ea98710a5d86cfd7eb35f7f0cd0178c2afdd1ab5ceb166bf3147498689d9b98b9f6470e9de673017e85606f827fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
